services:
  api:
    build:
      context: .
    command: ["npm", "run", "watch"]
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./:/root/project
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - CHOKIDAR_USEPOLLING=true

  postgres:
    image: postgres:17.5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: songer
      POSTGRES_DB: songerdb
    ports:
      - "5432:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
